### ISSUE TITLE
Need !hack module - must have!

### ISSUE THREAD

**Issue by kulverstukas1** [EvilzoneLabs/BeastBot#10]
Need !hack module - must have!

**Comment by chris2727** [comment]
I don't even know what that is suppose to do lol

**Comment by kulverstukas1** [comment]
Basically this: https://github.com/maxpowa/inumuta-modules/blob/master/hack.py

**Comment by kenjoe41** [comment]
Committed, test and revisions needed to close this.

**Comment by kulverstukas1** [comment]
Seems to be working good. Closing.
