### ISSUE TITLE
Bot Timeouts

### ISSUE THREAD

**Issue by Spacecow99** [EvilzoneLabs/BeastBot#13]
The bot times out many times and it bothers me. Should just rename it to cr4ziBot if it's gonna do that.

**Comment by chris2727** [comment]
I'm working on it

**Comment by chris2727** [comment]
possibly fixed by making it receive 256....
Still testing for confirmation

**Comment by chris2727** [comment]
possibly fixed in the new sqlite version of the bot.
Running the new bot and will see.

**Comment by chris2727** [comment]
nope.... bot still timeouts :/

**Comment by chris2727** [comment]
fixed
