### ISSUE TITLE
Bot stopped responding to urls

### ISSUE THREAD

**Issue by kulverstukas1** [EvilzoneLabs/BeastBot#19]
Whenever a URL is dropped on the channel, the bot doesn't say the title. It works in PM tho.

**Comment by kenjoe41** [comment]
I know where it broke. Preceeding it with the seen_record elif prolly broke it. the http line never hits the http elif.
I hope we find a better way to intergrate modules that process every line received from the irc in the new remake.
Those two elifs can be interchanged if the new rewrite won't be waited for..

**Comment by chris2727** [comment]
fixed in the sqlite version of the bot
