### ISSUE TITLE
Insult module

### ISSUE THREAD

**Issue by chris2727** [EvilzoneLabs/BeastBot#28]
"an insult module, usage would be via pm to EZBot and you would !insult user [channel] and it will give a random insult to that user in said channel, would be fun as the user will not know who insulted them, unless they use deductive reasoning of course" - DeepCopy

Hrmm.... Might be kind of fun to do this. May create it. Thanks for the suggestion DeepCopy.

**Comment by itpho3nix** [comment]
I would also like to add to this, would be fun to make customized insults so if a certain name is triggered such as !insult HTH #evilzone you can have one of the random options being "HTH is just mad because Xires is porking his mom"

**Comment by ibabushkin** [comment]
I wrote some code for this, but GitHub won't let me create a new pull-request until the old one is either accepted or rejected and I'm too lazy to resolve that now.

**Comment by chris2727** [comment]
I just accepted it you lazy mofo :P

**Comment by chris2727** [comment]
great job thewormkill.... (ibabushkin) It is working great. The module is now loaded up by default on the main bot.
