### ISSUE TITLE
Pastebin search module

### ISSUE THREAD

**Issue by chris2727** [EvilzoneLabs/BeastBot#30]
"Pastebin search module, may be nice to make a pastebin search module , where it utilizes, site:pastebin.com [searchterm]" - DeepCopy

Hrm... I don't know.. Maybe I might look into it. We will see. If any one else wants to build this, please feel free to do so.

**Comment by itpho3nix** [comment]
Well I figured it would be so close to the define module, the main differences is pulling like the first 3-5 links instead of the definition

**Comment by ibabushkin** [comment]
Considering the fact that it's as easy as http://pastebin.com/search?q=bla+bla , I'll start working on it.

**Comment by techb** [comment]
Is this being worked on? If not I'll do it.

**Comment by techb** [comment]
Nevermind, I just added it.

**Comment by ibabushkin** [comment]
Sigh, I was debugging the shit out of it on friday. And was absent for 1.5 days. And the next thing I see is my work being obsolete. Yay. Next time we should respect others' comments like "I'll work on it".

**Comment by techb** [comment]
We can still use yours instead if you want instead, the request hasn't been merged yet so you can still make a request.

**Comment by ibabushkin** [comment]
Yeah, I guess that's not that important anymore. I'll review yours now.
UPDATE: merged into `testing`.
