### ISSUE TITLE
Spell check module

### ISSUE THREAD

**Issue by chris2727** [EvilzoneLabs/BeastBot#31]
"how about a spell check add-on, whenever someone posts a misspelling, it'll say "did you mean: suggestion" idk if it'd work and how resource heavy it would be as it would have to read each line... Maybe have it process a string through google, and if google spits out did you mean it will respond with that. May be really memory intensive though. But then again I'm not much of a programmer..." - DeepCopy

Good idea. Possibly could integrate this with kulver's idea for a grammar nazi module

**Comment by ibabushkin** [comment]
Well, IMO grammar nazi will be a real challenge, whereas outsourcing the spellcheck should be do-able.

**Comment by chris2727** [comment]
Yes the grammar nazi will be very difficult... The english language is fucked....
"Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo" is a sentence that uses correct grammar.

**Comment by itpho3nix** [comment]
No its not :/

**Comment by chris2727** [comment]
yes it is....... 

https://simple.wikipedia.org/wiki/Buffalo_buffalo_Buffalo_buffalo_buffalo_buffalo_Buffalo_buffalo

**Comment by ibabushkin** [comment]
Basically, this discussion is not really productive. I guess we should close the issue.
