### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by techb** [EvilzoneLabs/BeastBot#36]
Can we use API keys? Say you have a module but it requires using an API to use it with a website your accessing, is that allowed? Would we need to provide our personal API key, make a new one for the bot, or have one of the owners of the bot make one and add it to the module?

**Comment by ibabushkin** [comment]
Why not? Just make sure that the API is _suitable_ for usage with the bot. For instance, if it limits the usage to 20 calls per day, it is probably a bit unreliable for us. Of course, this is a very exaggerated
example, but you get the idea.
