### ISSUE TITLE
Announce new posts

### ISSUE THREAD

**Issue by itpho3nix** [EvilzoneLabs/BeastBot#39]
Whenever a post is posted on EZ it will announce the thread. This could be in a specific channel or whatnot. Although this may need some API for it to list topics/posts that you have to be logged in to view. Obv. This wouldn't announce hidden boards live vip+ / group boards

**Comment by chris2727** [comment]
I have actually already made something to do this. It isnt a module yet, but I should be able to convert it. I'll give it a shot later.

**Comment by chris2727** [comment]
did it.. may need some work but it is operational and seems stable...
