### ISSUE TITLE
Issue with "seen" module

### ISSUE THREAD

**Issue by kh0fo** [EvilzoneLabs/BeastBot#43]
I've noticed an issue with the !seen command, since in the code for privacy reasons if the requested user's last words were on another channel than the one the !seen command was issued from the answer would be "seen in another channel saying:", whereas if a user was last seen on the same channel where the !seen command was issued from it still delivers the same message.

Here is the snippet I am talking about, that does not work:

``` python
def seen(line, irc):
    message, username, msgto = ircFunc.ircMessage(line)
    try:
        if message[1]:
            nick = message[1].strip().lower()
            values = get_seen_value(nick)
            if values[0] == msgto:
                channel = 'here'
            else:
                channel = 'another channel' #not mentioning channels for privacy
```

**Comment by chris2727** [comment]
Thanks for the update khofo! I believe this is due to the fact that it is not converting the channel to lowercase. This should be fixed in the next update of EZBot. Thank you

**Comment by kh0fo** [comment]
You're welcome, I'll consider this issue closed then
