### ISSUE TITLE
Make seen module

### ISSUE THREAD

**Issue by kulverstukas1** [EvilzoneLabs/BeastBot#7]
Make seen module.

**Comment by kenjoe41** [comment]
Commited, tests and edits requested inorder to close this.

**Comment by kulverstukas1** [comment]
I tested it a bit, seems to work from what I saw, however before closing this needs more thorough testing,because it didn't work when I was connected through KiwiiIRC.
I also committed some format changes...

**Comment by kenjoe41** [comment]
well, don't know how it went on your end but i tested with kiwiirc and the user coming through kiwiirc was logged and seen.
Prolly someone should try it out and we see.

**Comment by chris2727** [comment]
seems like it is working good.... Good job kulver and kenjoe... Closing the issue :)
